### ISSUE TITLE
能不能支持Deno部署？

### ISSUE THREAD

**Issue by anunol** [snakeying/flux-api-worker#2]
#### 描述：

Cloudflare（CF）阻止了来自Hugging Face Space的API访问，这让在该平台上使用OpenWebUI非常麻烦。为了绕过这个限制，我目前用Deno反向代理CF worker，这个过程比较繁琐。如果可以直接在Deno上部署会方便很多。Deno几乎与CF workers兼容，并且提供免费的KV存储。

#### 请求：

1. **Deno版本**：请研究并发布一个兼容Deno的版本，使用Deno的KV存储。
2. **API端点支持**：确保API能够同时支持`/v1/chat/completions`和`/v1/images/generations`端点。

这个改进将简化部署流程，并扩大服务的可访问性。谢谢！

**Comment by snakeying** [comment]
抱歉我使用过Deno。。。我不太清楚应该如何支持。。。
